import { 
  Rocket, 
  Brain, 
  Globe, 
  TrendingUp, 
  Cpu, 
  ShieldCheck, 
  Zap, 
  Target 
} from "lucide-react";
import { TimelineItem } from "@/components/ui/radial-orbital-timeline";

export const journeyData: TimelineItem[] = [
  {
    id: 1,
    title: "The Genesis",
    date: "August 2019",
    content: "BITSOL was founded with a single mission: to bridge the gap between traditional marketing and emerging AI technologies.",
    category: "Foundation",
    icon: Target,
    relatedIds: [2],
    status: "completed",
    energy: 100,
  },
  {
    id: 2,
    title: "Digital Expansion",
    date: "March 2020",
    content: "Rapidly scaled our web engineering department, delivering over 50 high-performance ecosystems during the global digital shift.",
    category: "Scaling",
    icon: Globe,
    relatedIds: [1, 3],
    status: "completed",
    energy: 90,
  },
  {
    id: 3,
    title: "AI Integration",
    date: "January 2021",
    content: "Launched our first proprietary neural network for predictive marketing analytics, setting a new standard for data-driven ROI.",
    category: "Innovation",
    icon: Brain,
    relatedIds: [2, 4],
    status: "completed",
    energy: 95,
  },
  {
    id: 4,
    title: "FinTech Breakthrough",
    date: "November 2022",
    content: "Successfully deployed AlphaTrade Pro, marking our entry into high-frequency algorithmic trading technology.",
    category: "FinTech",
    icon: TrendingUp,
    relatedIds: [3, 5],
    status: "completed",
    energy: 85,
  },
  {
    id: 5,
    title: "Nexus AI Engine",
    date: "June 2023",
    content: "Unveiled Nexus AI, our most powerful enterprise automation engine, currently powering 20+ global logistics fleets.",
    category: "Automation",
    icon: Cpu,
    relatedIds: [4, 6],
    status: "completed",
    energy: 100,
  },
  {
    id: 6,
    title: "Institutional Custody",
    date: "April 2024",
    content: "Released CryptoVault OS, providing institutional-grade digital asset security for emerging markets.",
    category: "Security",
    icon: ShieldCheck,
    relatedIds: [5, 7],
    status: "completed",
    energy: 90,
  },
  {
    id: 7,
    title: "The Global Hub",
    date: "September 2025",
    content: "Opening our second regional innovation hub to foster cross-border AI research and development.",
    category: "Expansion",
    icon: Rocket,
    relatedIds: [6, 8],
    status: "in-progress",
    energy: 70,
  },
  {
    id: 8,
    title: "Quantum Era",
    date: "January 2026",
    content: "Pioneering the integration of quantum-resistant algorithms across all BITSOL marketing and data ecosystems.",
    category: "Future",
    icon: Zap,
    relatedIds: [7],
    status: "pending",
    energy: 40,
  }
];
